global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-monitoring'
    metrics_path: '/actuator/prometheus'
    scheme: http
    bearer_token_file: '/monitoring/metrics.token'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'expenses_tracker'
