global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'expenses_tracker'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus-password'